version: '3.9'

services:
  kafka:
    container_name: kafka
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    ports:
      - 9092:9092
    volumes:
      - kafka_data:/bitnami
    depends_on:
      - zookeeper
    restart: unless-stopped

  zookeeper:
    image: docker.io/bitnami/zookeeper
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181
    volumes:
      - zookeeper_data:/bitnami
    restart: unless-stopped

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local